version: "3.8"

services:
  postgre:
    image: postgres:14
    container_name: postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine3.18
    container_name: redis
    ports:
      - "6378:6379"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRE=host=postgre user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
    depends_on:
      - postgre
      - redis
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
